# Specify service dependencies here if necessary
  # CircleCI maintains a library of pre-built images
  # documented at https://circleci.com/docs/2.0/circleci-images/
  # - image: circleci/mongo:3.4.4

# working_directory: ~/RA
jobs: 
  build:  
    working_directory: ~/end-to-end-tests
    docker:
            - image: circleci/node:10-browsers
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: start
        command: npm run dev
        background: true
    
    - run:
        name: set up
        command: |
          sudo npm i -g protractor
          sudo webdriver-manager update
          sudo webdriver-manager start
          background: true

    - run:
        name: run e2e test
        command:
          protractor conf.js
    # - store_test_results:
    #       path: /tmp/test-results/