# Specify service dependencies here if necessary
  # CircleCI maintains a library of pre-built images
  # documented at https://circleci.com/docs/2.0/circleci-images/
  # - image: circleci/mongo:3.4.4

# working_directory: ~/RA
jobs: 
  build:  
    working_directory: ~/end-to-end-tests
    docker:
            - image: circleci/node:jessie-browsers
    steps:
    - checkout
    - run: mkdir test-reports
    - run:
        name: Download Selenium
        command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
    - run:
        name: Start Selenium
        command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        background: true
    - run:
        name: install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: start
        command: npm run dev
        background: true
    
    - run:
        name: set up
        command: |
          sudo npm i -g protractor
          #sudo webdriver-manager update
          #sudo webdriver-manager start
        
  
    - run:
        name: run e2e test
        command:
          protractor conf.js
    - store_test_results:
          path: /target/